//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace Net.Mokon.Edu.Unh.CS.AI.GridWorld {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Map {
        
        private int versionField;
        
        private System.DateTime dateField;
        
        private Generator generatorField;
        
        private int seedField;
        
        private int heightField;
        
        private int widthField;
        
        private Coord startField;
        
        private Coord goalField;
        
        private int lOSField;
        
        private bool lOSFieldSpecified;
        
        private double optimalSolutionCostField;
        
        private bool optimalSolutionCostFieldSpecified;
        
        private string tilesField;
        
        private ChangeList changeListField;
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public Generator Generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        
        /// <remarks/>
        public int Seed {
            get {
                return this.seedField;
            }
            set {
                this.seedField = value;
            }
        }
        
        /// <remarks/>
        public int Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public int Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public Coord Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public Coord Goal {
            get {
                return this.goalField;
            }
            set {
                this.goalField = value;
            }
        }
        
        /// <remarks/>
        public int LOS {
            get {
                return this.lOSField;
            }
            set {
                this.lOSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LOSSpecified {
            get {
                return this.lOSFieldSpecified;
            }
            set {
                this.lOSFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double OptimalSolutionCost {
            get {
                return this.optimalSolutionCostField;
            }
            set {
                this.optimalSolutionCostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OptimalSolutionCostSpecified {
            get {
                return this.optimalSolutionCostFieldSpecified;
            }
            set {
                this.optimalSolutionCostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Tiles {
            get {
                return this.tilesField;
            }
            set {
                this.tilesField = value;
            }
        }
        
        /// <remarks/>
        public ChangeList ChangeList {
            get {
                return this.changeListField;
            }
            set {
                this.changeListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    public enum Generator {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MAI-Dynamic-Chokepoint")]
        MAIDynamicChokepoint,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MAI-Static-Map")]
        MAIStaticMap,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("MAI-Dynamic-Rooms")]
        MAIDynamicRooms,
        
        /// <remarks/>
        Custom,
        
        /// <remarks/>
        Experimental,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Coord {
        
        private int xField;
        
        private int yField;
        
        /// <remarks/>
        public int X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public int Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Step {
        
        private int stepNumField;
        
        private Coord[] changesField;
        
        /// <remarks/>
        public int StepNum {
            get {
                return this.stepNumField;
            }
            set {
                this.stepNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Tile", IsNullable=false)]
        public Coord[] Changes {
            get {
                return this.changesField;
            }
            set {
                this.changesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeList {
        
        private bool repeatableField;
        
        private bool blockOnAgentField;
        
        private Step[] stepsField;
        
        /// <remarks/>
        public bool Repeatable {
            get {
                return this.repeatableField;
            }
            set {
                this.repeatableField = value;
            }
        }
        
        /// <remarks/>
        public bool BlockOnAgent {
            get {
                return this.blockOnAgentField;
            }
            set {
                this.blockOnAgentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Steps")]
        public Step[] Steps {
            get {
                return this.stepsField;
            }
            set {
                this.stepsField = value;
            }
        }
    }
}
